### ISSUE TITLE
Documentation usage as a library

### ISSUE THREAD

**Issue by rzerres** [mambisi/escanor#1]
Hey mambisi,

I'd like to integrate escanor in a rust project.
The application will communicate with an external api. This api is streaming as struct (including room_id, room_name). When parsing the struct I'd like to store unknown/new keys (room_id) and corresponding values in memory. Key/Value storage is an optimal implementation for this purpose.

I have seen the cli usage example in the wiki. But haven't found an example or usage / API documentation if i want to use escanor as a module inside my rust code. 

Obviousliy, i would have to dig into the code (db.rs) to find the corresponding functions. But i do think, as the project is evolving, my question will arise to others as well. Is this kind of documentation planned? Do you have a short intro?

Greetings
Ralf

PS: in go there is pogreb. You may have a look at there usage example....
https://github.com/akrylysov/pogreb

**Comment by mambisi** [comment]
Escanor uses the redis protocol, so any redis rust library can interface with it,
check out [redis-rs](https://github.com/mitsuhiko/redis-rs),
example:
```rust
// connect to redis
    let client = redis::Client::open("redis://127.0.0.1/")?;
    let mut con = client.get_connection()?;
    // throw away the result, just make sure it does not fail
    let _ : () = con.set("my_key", 42)?;
    // read back the key and return it.  Because the return value
    // from the function is a result for integer this will automatically
    // convert into one.
    con.get("my_key")
```
